export const PORTFOLIO_ACTION_TYPES = {
    SET_PORTFOLIO: 'SET_PORTFOLIO',
    FETCH_PORTFOLIO_START: 'FETCH_PORTFOLIO_START',
    FETCH_PORTFOLIO_SUCCESS: 'FETCH_PORTFOLIO_SUCCESS',
    FETCH_PORTFOLIO_FAILED: 'FETCH_PORTFOLIO_FAILED'
}